"""empty message

Revision ID: 70a66190aa1b
Revises: 
Create Date: 2022-01-04 19:35:15.641059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a66190aa1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rabbitDate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitKinds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinds_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitTime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_slot', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitWeather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitDateRanking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinds_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('date_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['rabbitDate.id'], ),
    sa.ForeignKeyConstraint(['kinds_id'], ['rabbitKinds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitMenu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('toggle_rating', sa.Integer(), nullable=True),
    sa.Column('world_rating', sa.Integer(), nullable=True),
    sa.Column('world_ranking', sa.Integer(), nullable=True),
    sa.Column('kinds_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kinds_id'], ['rabbitKinds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitTimeRanking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinds_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('time_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kinds_id'], ['rabbitKinds.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['rabbitTime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitWeatherRanking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinds_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('weather_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kinds_id'], ['rabbitKinds.id'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['rabbitWeather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rabbitWeatherRanking')
    op.drop_table('rabbitTimeRanking')
    op.drop_table('rabbitMenu')
    op.drop_table('rabbitDateRanking')
    op.drop_table('rabbitWeather')
    op.drop_table('rabbitTime')
    op.drop_table('rabbitKinds')
    op.drop_table('rabbitDate')
    # ### end Alembic commands ###
