"""empty message

Revision ID: a0e4fbe0b130
Revises: fca7bd849e94
Create Date: 2021-12-29 21:18:05.450413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e4fbe0b130'
down_revision = 'fca7bd849e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rabbitTime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_slot', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitTimeRanking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinds_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('time_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kinds_id'], ['rabbitKinds.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['rabbitDate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rabbitTimeRanking')
    op.drop_table('rabbitTime')
    # ### end Alembic commands ###
