"""empty message

Revision ID: a4280757e07e
Revises: e014cc02e053
Create Date: 2021-12-29 20:52:54.281093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4280757e07e'
down_revision = 'e014cc02e053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rabbitWeather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitWeatherRanking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinds_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('weather_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kinds_id'], ['rabbitKinds.id'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['rabbitWeather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rabbitWeatherRanking')
    op.drop_table('rabbitWeather')
    # ### end Alembic commands ###
