"""empty message

Revision ID: b3ccb463fb13
Revises: a0e4fbe0b130
Create Date: 2021-12-30 16:08:59.734137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ccb463fb13'
down_revision = 'a0e4fbe0b130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rabbitMenu', sa.Column('world_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rabbitMenu', 'world_rating')
    # ### end Alembic commands ###
