"""empty message

Revision ID: fca7bd849e94
Revises: 741803a98dfd
Create Date: 2021-12-29 20:57:17.155732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca7bd849e94'
down_revision = '741803a98dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rabbitDate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rabbitDateRanking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinds_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('date_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['rabbitDate.id'], ),
    sa.ForeignKeyConstraint(['kinds_id'], ['rabbitKinds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rabbitDateRanking')
    op.drop_table('rabbitDate')
    # ### end Alembic commands ###
